# Example xAI provider configuration for ~/.codex/config.toml
# 
# This configuration enables Codex to work with xAI's API endpoints.
# Make sure to export your API key: export XAI_API_KEY="your-key-here"

# Set the default model and provider
model = "grok-code-fast-1"
model_provider = "api_x"

# Define the xAI provider
[model_providers.api_x]
name = "xAI"
base_url = "https://api.x.ai/v1"
env_key = "XAI_API_KEY"
wire_api = "chat"           # Use OpenAI Chat Completions format
query_params = {}           # No additional query parameters needed
http_headers = {}           # No additional headers needed
request_max_retries = 4     # Retry failed requests up to 4 times
stream_max_retries = 10     # Retry dropped streams up to 10 times

# Optional: Define profiles for different xAI models
[profiles.grok-fast]
model = "grok-code-fast-1"
model_provider = "api_x"
approval_policy = "untrusted"

[profiles.grok-vision]
model = "grok-2-vision-1212"
model_provider = "api_x"
approval_policy = "untrusted"

# Optional: Configure additional settings
[history]
persistence = "save-all"    # Save conversation history

[tui]
notifications = true        # Enable desktop notifications